Refactor sysmaint-boot, fix bugs

diff --git a/usr/libexec/user-sysmaint-split/sysmaint-boot b/usr/libexec/user-sysmaint-split/sysmaint-boot
--- a/usr/libexec/user-sysmaint-split/sysmaint-boot
+++ b/usr/libexec/user-sysmaint-split/sysmaint-boot
@@ -12,7 +12,7 @@ set -o pipefail
 echo "$0: INFO: START"
 
 error_handler() {
-   last_exit_code="$?"
+   local last_exit_code="$?"
    echo "\
 ###
 $0: ERROR:
@@ -25,7 +25,7 @@ failed with exit code '$last_exit_code'.
 trap error_handler ERR
 
 exit_handler() {
-   local exit_code=$?
+   local exit_code="$?"
    echo "INFO: If installed, rads (Ram Adjusted Desktop Starter) should be starting, ok."
    echo "INFO: (Because sysmaint-boot.target runs 'Before=rads.service' and 'Wants=rads.service'.)"
    if [ "$exit_code" = "0" ]; then
@@ -44,6 +44,7 @@ wayland_enabled='no'
 if [ -f '/var/lib/user-sysmaint-split/wayland-enabled' ]; then
    wayland_enabled='yes'
 fi
+sysmaint_passwordless='true'
 
 echo "INFO: default_display_manager: '$default_display_manager'"
 echo "INFO: wayland_enabled: '$wayland_enabled'"
@@ -53,63 +54,50 @@ if accountctl sysmaint is-pass-locked; then
    sysmaint_account_already_locked=yes
 fi
 
-if ! [[ "${kernel_cmdline}" =~ 'boot-role=sysmaint' ]]; then
-   echo "INFO: user mode boot detected. (Not sysmaint boot mode.)"
-   echo "INFO: (kernel parameter 'boot-role=sysmaint' is not present, ok.)"
-
+lock_sysmaint_account() {
    echo "INFO: sysmaint_account_already_locked: '$sysmaint_account_already_locked'"
    if [ "$sysmaint_account_already_locked" = "no" ]; then
       echo "INFO: Therefore, locking account 'sysmaint' (and deleting auto generated sysmaint login manager configuration files)."
       accountctl sysmaint lock-pass
    fi
+}
 
+remove_sysmaint_autologin_files() {
    safe-rm -f '/etc/lightdm/lightdm.conf.d/60_sysmaint-boot.conf'
-   # Typically files under /etc/sddm.conf.d are NOT prefixed with a number, for
-   # instance KDE generates an /etc/sddm.conf.d/kde_settings.conf file, thus
-   # to get this file to be loaded last we have to use a name that sorts last
-   # in the alphabet without using a number prefix.
    safe-rm -f '/etc/sddm.conf.d/z-sysmaint-boot.conf'
-   exit 0
-fi
+}
 
-echo "INFO: sysmaint boot mode detected."
-echo "INFO: (kernel parameter 'boot-role=sysmaint' present, ok.)"
+detect_sysmaint_passwordless() {
+   if accountctl sysmaint is-pass-empty; then
+      echo "INFO: account 'sysmaint' is passwordless."
+      sysmaint_passwordless='true'
+   else
+      echo "INFO: account 'sysmaint' is password protected."
+      sysmaint_passwordless=false
+   fi
+}
 
-## Unlocking account 'sysmaint'.
-accountctl sysmaint unlock-pass
-
-if accountctl sysmaint is-pass-empty; then
-   echo "INFO: account 'sysmaint' is passwordless."
-   sysmaint_passwordless=true
-else
-   echo "INFO: account 'sysmaint' is password protected."
-   sysmaint_passwordless=false
-fi
-
-if [ "${default_display_manager}" = 'lightdm' ]; then
-   mkdir -p '/etc/lightdm/lightdm.conf.d'
-
-   if [ "${sysmaint_passwordless}" = "true" ]; then
-      if [ "${wayland_enabled}" = 'yes' ]; then
-         echo "[Seat:*]
+write_lightdm_enable_autologin_config() {
+   if [ "${wayland_enabled}" = 'yes' ]; then
+      echo "[Seat:*]
 autologin-user=sysmaint
 autologin-session=sysmaint-session-wayland" \
-            | sponge -- '/etc/lightdm/lightdm.conf.d/60_sysmaint-boot.conf'
-      else
-         echo "[Seat:*]
+         | sponge -- '/etc/lightdm/lightdm.conf.d/60_sysmaint-boot.conf'
+   else
+      echo "[Seat:*]
 autologin-user=sysmaint
 autologin-session=sysmaint-session" \
-            | sponge -- '/etc/lightdm/lightdm.conf.d/60_sysmaint-boot.conf'
-      fi
-   else
-      ## Prevent autologin in this instance, or the normal user account will
-      ## end up logged in.
-      echo "[Seat:*]
-autologin-user=" \
          | sponge -- '/etc/lightdm/lightdm.conf.d/60_sysmaint-boot.conf'
    fi
-   echo "INFO: Created file: '/etc/lightdm/lightdm.conf.d/60_sysmaint-boot.conf'"
+}
 
+write_lightdm_disable_autologin_config() {
+   echo "[Seat:*]
+autologin-user=" \
+      | sponge -- '/etc/lightdm/lightdm.conf.d/60_sysmaint-boot.conf'
+}
+
+write_lightdm_sysmaint_default_session_config() {
    if [ -d '/home/sysmaint' ]; then
       if [ "${wayland_enabled}" = 'yes' ]; then
          echo "[Desktop]
@@ -125,31 +113,34 @@ Session=sysmaint-session" \
    else
       echo "WARNING: Folder '/home/sysmaint' does not exist. Therefore, file '/home/sysmaint/.dmrc' has not been created."
    fi
-elif [ "${default_display_manager}" = 'sddm' ]; then
-   mkdir -p '/etc/sddm.conf.d'
+}
 
-   if [ "${sysmaint_passwordless}" = "true" ]; then
-      if [ "${wayland_enabled}" = 'yes' ]; then
-         echo "[Autologin]
+write_sddm_enable_autologin_config() {
+   # Typically files under /etc/sddm.conf.d are NOT prefixed with a number, for
+   # instance KDE generates an /etc/sddm.conf.d/kde_settings.conf file, thus
+   # to get this file to be loaded last we have to use a name that sorts last
+   # in the alphabet without using a number prefix.
+   if [ "${wayland_enabled}" = 'yes' ]; then
+      echo "[Autologin]
 User=sysmaint
 Session=sysmaint-session-wayland.desktop" \
-            | sponge -- '/etc/sddm.conf.d/z-sysmaint-boot.conf'
-      else
-         echo "[Autologin]
+         | sponge -- '/etc/sddm.conf.d/z-sysmaint-boot.conf'
+   else
+      echo "[Autologin]
 User=sysmaint
 Session=sysmaint-session.desktop" \
-            | sponge -- '/etc/sddm.conf.d/z-sysmaint-boot.conf'
-      fi
-   else
-      ## Prevent autologin in this instance, or the normal user account will
-      ## end up logged in
-      echo "[Autologin]
-User=
-Session=" \
          | sponge -- '/etc/sddm.conf.d/z-sysmaint-boot.conf'
    fi
-   echo "INFO: Created file: '/etc/sddm.conf.d/z-sysmaint-boot.conf'"
+}
 
+write_sddm_disable_autologin_config() {
+   echo "[Autologin]
+User=
+Session=" \
+      | sponge -- '/etc/sddm.conf.d/z-sysmaint-boot.conf'
+}
+
+write_sddm_sysmaint_default_session_config() {
    if [ "${wayland_enabled}" = 'yes' ]; then
       echo "[Last]
 User=sysmaint
@@ -162,4 +153,62 @@ Session=/usr/share/xsessions/sysmaint-session.desktop" \
          | sponge -- '/var/lib/sddm/state.conf'
    fi
    echo "INFO: Created file: '/var/lib/sddm/state.conf'"
-fi
+}
+
+handle_boot() {
+   if ! [[ "${kernel_cmdline}" =~ 'boot-role=sysmaint' ]]; then
+      echo "INFO: user mode boot detected. (Not sysmaint boot mode.)"
+      echo "INFO: (kernel parameter 'boot-role=sysmaint' is not present, ok.)"
+      lock_sysmaint_account
+      remove_sysmaint_autologin_files
+      exit 0
+   fi
+
+   echo "INFO: sysmaint boot mode detected."
+   echo "INFO: (kernel parameter 'boot-role=sysmaint' present, ok.)"
+
+   ## Unlocking account 'sysmaint'.
+   accountctl sysmaint unlock-pass
+   detect_sysmaint_passwordless
+
+   if [ "${default_display_manager}" = 'lightdm' ]; then
+      mkdir -p '/etc/lightdm/lightdm.conf.d'
+
+      if [ "${sysmaint_passwordless}" = "true" ]; then
+         write_lightdm_enable_autologin_config
+      else
+         ## Prevent autologin in this instance, or the normal user account will
+         ## end up logged in.
+         write_lightdm_disable_autologin_config
+      fi
+      echo "INFO: Created file: '/etc/lightdm/lightdm.conf.d/60_sysmaint-boot.conf'"
+
+      write_lightdm_sysmaint_default_session_config
+   elif [ "${default_display_manager}" = 'sddm' ]; then
+      mkdir -p '/etc/sddm.conf.d'
+
+      if [ "${sysmaint_passwordless}" = "true" ]; then
+         write_sddm_enable_autologin_config
+      else
+         ## Prevent autologin in this instance, or the normal user account will
+         ## end up logged in
+         write_sddm_disable_autologin_config
+      fi
+      echo "INFO: Created file: '/etc/sddm.conf.d/z-sysmaint-boot.conf'"
+
+      write_sddm_sysmaint_default_session_config
+   fi
+}
+
+sysmaint_boot() {
+   local mode="$1"
+   case "${mode}" in
+      'handle-boot') handle_boot;;
+      'cleanup-autologin') remove_sysmaint_autologin_files;;
+      *)
+         echo "$0: ERROR: Invalid mode provided.";
+         exit 1;;
+   esac
+}
+
+sysmaint_boot "$@"
