split into prerm and postrm

diff --git a/debian/user-sysmaint-split.prerm b/debian/user-sysmaint-split.prerm
--- a/debian/user-sysmaint-split.prerm
+++ b/debian/user-sysmaint-split.prerm
@@ -15,20 +15,26 @@ true "
 #####################################################################
 "
 
+if [ "$1" = 'remove' ] || [ "$1" = 'purge' ]; then
+   ## TODO: permission-hardener
+   ## Undo /usr/lib/permission-hardener.d/20_user-sysmaint-split.conf
+   ## Until the following has been implemented:
+   ## Reset file attributes if no configuration matches #286
+   ## https://github.com/Kicksecure/security-misc/pull/286
+   ##
+   ## Fail closed. (Without '|| true'.)
+   ## Because if failing open, the user might lock oneself out.
+   permission-hardener disable /usr/bin/sudo
+   permission-hardener disable /bin/sudo
+   permission-hardener disable /usr/bin/pkexec
+   permission-hardener disable /bin/pkexec
+fi
+
 true "INFO: debhelper beginning here."
 
 #DEBHELPER#
 
 true "INFO: Done with debhelper."
-
-if command -v update-grub >/dev/null 2>&1; then
-   update-grub || \
-      echo "$DPKG_MAINTSCRIPT_PACKAGE $DPKG_MAINTSCRIPT_NAME ERROR: Running \
-'update-grub' failed with exit code $?. $DPKG_MAINTSCRIPT_PACKAGE is most \
-likely only the trigger, not the cause. Unless you know this is not an issue, \
-you should fix running 'update-grub', otherwise your system might no longer \
-boot." >&2
-fi
 
 true "
 #####################################################################
